version: "3"
services:
  portainer-ce:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - '9000:9000'
      volumes:
        - '$DOCKERDIR/portainer/data:/data'
        - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped
    
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/root/.docker/config.json:/config.json'
    restart: unless-stopped

  eclipse-mosquitto:
    container_name: MQTT
    image: eclipse/mosquitto
    restart: unless-stopped
    network_mode: host
    ports:
      - '1883:1883'
    volumes:
      - '$DOCKERDIR/mosquitto:/mosquitto/'
  zigbee2mqtt:
    container_name: zigbee2mqtt
    network_mode: host
    restart: unless-stopped
    volumes:
      - '$DOCKERDIR/zigbee2mqtt/data:/ap/data'
    environment:
      - TZ=$TZ
    
  scrypted:
    container_name: scrypted
    image: koush/scrypted
    volumes:
      - '~/.scrypted/volume:/server/volume'
    restart: unless-stopped
    network_mode: host

  linuxserver: 
    container_name: heimdall
    image: 'lscr.io/linuxserver/heimdall:latest'
    volumes:
      - '$DOCKERDIR/heimdall:/config'
    environment:
      - PGID=1000
      - PUID=1000
    ports:
      - '8201:80'
      - '8200:443'
    restart: unless-stopped
    
    
    
