version: "3.7"
services:
  portainer-ce:
    container_name: portainer
    image: portainer/portainer-ce:latest
    ports:
      - '9000:9000'
    volumes:
      - '/home/$USER/docker/portainer/data:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
    restart: unless-stopped