version: "3.7"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/root/.docker/config.json:/config.json'
    restart: unless-stopped